# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.23.5  # Compatible with pandas 1.5.3
        pip install -r requirements.txt  # Contains pandas==1.5.3
        pip install flake8 pytest  # Testing and linting tools
    
    - name: Lint with flake8
      run: |
        echo "Running strict linting (will fail on errors)"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        echo "Running warning-level linting"
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest -v  # Verbose mode shows individual test results
